# Generated by Django 4.1.2 on 2022-10-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='slug',
            field=models.SlugField(help_text='Добавлять одним словом и с маленькой буквы', max_length=15),
        ),
    ]
