# Generated by Django 4.1.2 on 2022-10-22 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MastersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=20, verbose_name='Отчество')),
                ('photo', models.ImageField(upload_to='masters/%Y/%m/%d', verbose_name='Картинка')),
                ('speciality', models.CharField(max_length=50, verbose_name='Специальность')),
                ('experience', models.DateField(verbose_name='Когда начало карьеры')),
                ('slug', models.SlugField(max_length=150, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
        migrations.CreateModel(
            name='PartOfBodyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Часть тела')),
            ],
            options={
                'verbose_name': 'Часть тела',
                'verbose_name_plural': 'Части тела',
            },
        ),
        migrations.CreateModel(
            name='ProblemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Проблема')),
                ('part_of_the_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesthetics_clinic.partofbodymodel', verbose_name='Части тела')),
            ],
            options={
                'verbose_name': 'Проблема с кожей',
                'verbose_name_plural': 'Проблемы с кожей',
            },
        ),
        migrations.CreateModel(
            name='ProceduresModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(max_length=5000, verbose_name='Описание')),
                ('indications_for', models.TextField(max_length=1000, verbose_name='Для кого подходит')),
                ('contraindications', models.TextField(max_length=1000, verbose_name='Для кого не подходит')),
                ('soviet_of_expert', models.TextField(max_length=1500, verbose_name='Совет эксперта')),
                ('protocol', models.TextField(max_length=3000, verbose_name='Протокол')),
                ('result', models.TextField(max_length=1000, verbose_name='Результат')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('problems', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aesthetics_clinic.problemsmodel', verbose_name='Проблемы')),
            ],
            options={
                'verbose_name': 'Процедура',
                'verbose_name_plural': 'Процедуры',
            },
        ),
    ]
