# Generated by Django 4.1.2 on 2022-10-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesthetics_clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partofbodymodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, verbose_name='Слаг'),
        ),
        migrations.AddField(
            model_name='problemsmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, verbose_name='Слаг'),
        ),
        migrations.AddField(
            model_name='proceduresmodels',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='mastersmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, verbose_name='Слаг'),
        ),
    ]
