# Generated by Django 4.1.2 on 2022-10-22 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryLineModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(max_length=5000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Косметическая линия',
                'verbose_name_plural': 'Косметические линии',
            },
        ),
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(max_length=5000, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='prod/%Y/%m/%d', verbose_name='Картинка')),
                ('consist', models.TextField(max_length=300, verbose_name='Состав')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('available', models.BooleanField(default=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categorylinemodels')),
            ],
            options={
                'verbose_name': 'Косметика',
                'verbose_name_plural': 'Косметика',
            },
        ),
    ]
